name: sundaymart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  intl: ^0.17.0
  flash: ^3.0.5+1
  lottie: ^2.1.0
  get_it: ^7.2.0
  shimmer: ^2.0.0
  location: ^4.4.0
  auto_route: ^5.0.4
  share_plus: ^6.3.0
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
#  google_fonts: ^3.0.1
  google_fonts: ^4.0.4
  url_launcher: ^6.1.7
  flutter_remix: ^0.0.3
  osm_nominatim: ^2.0.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.3.0
  flutter_riverpod: ^2.1.3
  connectivity_plus: ^3.0.2
  freezed_annotation: ^2.2.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.0.15
  firebase_messaging: ^14.2.0
  google_maps_flutter: ^2.2.2
  cached_network_image: ^3.2.3
  flutter_native_splash: ^2.2.16
  flutter_login_facebook: ^1.8.0
  flutter_calendar_carousel: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  auto_route_generator: ^5.0.3
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/all/
    - assets/images/dark_mode/
    - assets/images/light_mode/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/images/all/app_logo.png'


flutter_native_splash:
  android_12:
  fullscreen: true
  background_image: 'assets/images/all/sundaymart_splash.png'
