// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlHYHbD7rwU4SI1WFW0BJ-tSBztxRtgec',
    appId: '1:881949895153:web:fe92a363f8429f6cbbbc50',
    messagingSenderId: '881949895153',
    projectId: 'trolley-990b2',
    authDomain: 'trolley-990b2.firebaseapp.com',
    storageBucket: 'trolley-990b2.appspot.com',
    measurementId: 'G-J9HKKG04DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqDUTVDwpMJuSB6r0IckAy_lavXH-BQhE',
    appId: '1:881949895153:android:c4905e48688c48bdbbbc50',
    messagingSenderId: '881949895153',
    projectId: 'trolley-990b2',
    storageBucket: 'trolley-990b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoyHD8begthN-xZJJe6IA9XvmZzTCp1bw',
    appId: '1:881949895153:ios:1ae86add4d65eb96bbbc50',
    messagingSenderId: '881949895153',
    projectId: 'trolley-990b2',
    storageBucket: 'trolley-990b2.appspot.com',
    iosClientId: '881949895153-60hpc07bu495uhu1fj9jcmluun6n45sm.apps.googleusercontent.com',
    iosBundleId: 'com.trolley',
  );
}
